M48
; DRILL file {KiCad 8.0.8} date 2026-01-21T18:00:21+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-21T18:00:21+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X82.61Y-94.535
X88.39Y-94.535
T2
X90.75Y-76.85
M30
